"""Generate THIS agent's .env.example from its .env, with secrets blanked.

    python tools/make_env_example.py

`.env` is gitignored; `.env.example` is what a fresh clone gets. Hand-maintained
examples drift from the real file within about two credential changes, and the
failure is quiet: someone clones, copies the example, and is missing three keys
nobody remembers adding. Generating removes the possibility.

REDACTION IS DELIBERATELY GREEDY — the key name is matched on *contains*, not
*ends with*. The first version of this anchored on the end of the name and
published `R2_ACCESS_KEY_ID` in full, because that is the one credential whose
name ends in `_ID` rather than in the giveaway word. A false positive costs a
blank line in a template someone fills in; a false negative publishes a live key.
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

AGENT_ROOT = Path(__file__).resolve().parent.parent

SECRET_KEY = re.compile(
    r"KEY|TOKEN|SECRET|PASSWORD|CREDENTIAL|DATABASE_URL|_PW\b"
    r"|^NEON_|^TELEGRAM_CHAT_ID$|^R2_BUCKET_ENDPOINT$",
    re.IGNORECASE,
)
SECRET_VALUE = re.compile(
    r"^(sk-|hf_|xkeysib-|tvly-|EAA|IGAA|THAA|cfat_|gsk_|postgresql://|github_pat_"
    r"|rl_|reddit-api-|twitterapis-|AIza)"
    r"|^\d{8,}:[A-Za-z0-9_-]{30,}$"   # telegram bot token
    r"|^[0-9a-f]{32,}$"               # bare hex secrets (R2 access key, app secrets)
)


def redact(line: str) -> str:
    s = line.strip()
    if not s or s.startswith("#") or "=" not in s:
        return line
    key, value = s.split("=", 1)
    key, value = key.strip(), value.strip()
    if not value:
        return line
    if SECRET_KEY.search(key) or SECRET_VALUE.match(value):
        return f"{key}="
    return line


def main() -> int:
    src = AGENT_ROOT / ".env"
    if not src.exists():
        sys.exit(f"no .env at {src}")
    original = src.read_text(encoding="utf-8-sig").splitlines()
    out = [redact(line) for line in original]
    header = (
        "# GENERATED by tools/make_env_example.py from this folder's .env.\n"
        "# Do not hand-edit: edit .env, then regenerate. Secret values are blanked.\n"
        "# Copy to .env and fill in every empty value.\n"
    )
    (AGENT_ROOT / ".env.example").write_text(header + "\n".join(out) + "\n", encoding="utf-8")
    blanked = sum(1 for a, b in zip(original, out, strict=True) if a != b)
    print(f"  ok   {AGENT_ROOT.name}/.env.example  ({blanked} value(s) blanked)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
